name: tronv

services:
  backend:
    container_name: tronv-backend
    image: tronv-backend:dev
    build:
      context: ../../
      dockerfile: deployments/dev/backend/Dockerfile
      tags:
        - "tronv-backend:dev"
    volumes:
      - ../..:/app
      - backend-data:/run/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URL: postgresql+psycopg://root:root@postgres/root
      PAGE_SIZE: 20
    command: tronv-dev
    ports:
      - 8000:8000

  postgres:
    image: postgres:16.3-alpine3.19
    container_name: tronv-postgres
    labels:
      deployment: dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: pg_isready -d root -U root
      start_period: 1m
      start_interval: 1s
      interval: 5s

volumes:
  backend-data: null

  postgres-data:
    labels:
      db: true
