"""use logs

Revision ID: 40b3d9535204
Revises: 37787beba486
Create Date: 2025-03-26 12:38:03.788271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '40b3d9535204'
down_revision: str | None = '37787beba486'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_view_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('address_text', sa.String(), nullable=False),
    sa.Column('trx_balance', sa.DECIMAL(), nullable=True),
    sa.Column('bandwidth', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('viewing_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('request_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('address_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trx_balance', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bandwidth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('energy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='request_logs_pkey')
    )
    op.drop_table('address_view_logs')
    # ### end Alembic commands ###
