"""add all tables

Revision ID: 8bef3c64dd83
Revises:
Create Date: 2025-03-26 12:04:59.394498

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "8bef3c64dd83"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("address_text", sa.String(), nullable=False),
        sa.Column("trx_balance", sa.DECIMAL(), nullable=False),
        sa.Column("bandwidth", sa.Integer(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("request_logs")
    # ### end Alembic commands ###
